/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/zwYHi7LP35B
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { JSX, SVGProps } from "react"

export function Chat() {
  return (
    <div className="flex h-[90vh] max-h-[90vh] flex-col bg-gray-50 dark:bg-gray-900">
      <header className="flex items-center justify-between bg-gray-100 px-4 py-3 dark:bg-gray-800">
        <div className="flex items-center space-x-2">
          <BotIcon className="h-6 w-6 text-gray-500 dark:text-gray-400" />
          <h1 className="text-lg font-semibold text-gray-900 dark:text-gray-50">ChatGPT</h1>
        </div>
      </header>
      <div className="flex-1 overflow-y-auto px-4 py-6">
        <div className="space-y-4">
          <div className="flex items-start space-x-3">
            <BotIcon className="mt-1 h-6 w-6 flex-shrink-0 text-gray-500 dark:text-gray-400" />
            <div className="max-w-[80%] rounded-lg bg-gray-100 p-3 text-gray-900 dark:bg-gray-800 dark:text-gray-50">
              <p>Hello! I'm ChatGPT, an AI assistant. How can I help you today?</p>
            </div>
          </div>
          <div className="flex justify-end space-x-3">
            <div className="max-w-[80%] rounded-lg bg-blue-500 p-3 text-gray-50">
              <p>Hi ChatGPT! I'd like to learn more about your capabilities.</p>
            </div>
            <UserIcon className="mt-1 h-6 w-6 flex-shrink-0 text-gray-500 dark:text-gray-400" />
          </div>
          <div className="flex items-start space-x-3">
            <BotIcon className="mt-1 h-6 w-6 flex-shrink-0 text-gray-500 dark:text-gray-400" />
            <div className="max-w-[80%] rounded-lg bg-gray-100 p-3 text-gray-900 dark:bg-gray-800 dark:text-gray-50">
              <p>
                As an AI assistant, I have a wide range of capabilities. I can help with research, analysis, writing,
                coding, and much more. What kind of task did you have in mind?
              </p>
            </div>
          </div>
        </div>
      </div>
      <div className="bg-gray-100 px-4 py-3 dark:bg-gray-800">
        <div className="flex items-center space-x-2">
          <Input
            className="flex-1 rounded-md border-gray-300 bg-white px-3 py-2 text-gray-900 shadow-sm focus:border-blue-500 focus:ring-blue-500 dark:border-gray-700 dark:bg-gray-900 dark:text-gray-50"
            placeholder="Type your message..."
            type="text"
          />
          <Button size="sm" variant="secondary">
            Send
          </Button>
        </div>
      </div>
    </div>
  )
}

function BotIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 8V4H8" />
      <rect width="16" height="12" x="4" y="8" rx="2" />
      <path d="M2 14h2" />
      <path d="M20 14h2" />
      <path d="M15 13v2" />
      <path d="M9 13v2" />
    </svg>
  )
}


function UserIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
